### ISSUE TITLE
performance when using gradation for image ?

### ISSUE THREAD

**Issue by natsupy** [eral/UnityUIExtention#1]
Hi, this is awesome, but when i'm using gradation for image and moving it, performance using is so hight, like this, so what am i mistake and can fix it ? Thank you so much !
http://i.imgur.com/HwjxIxC.png

**Comment by eral** [comment]
Hi.

Gradation.ModifyMesh() is very heavy function.
That's heavy in particular in a case with a lot of vertex of a image (or a text) component.
How long is the number of a image (or a text) component vertices?
It might be performance up if you add a canvas component in the same game object.


Native language text(Japanese)
使ってくれてありがとうございます。
Gradation.ModifyMesh()はとても重い関数です。
画像(やテキスト)コンポーネントの頂点が多い場合は特にです。
画像(やテキスト)コンポーネントの頂点数はどれぐらいですか？
もしかしたら同じゲームオブジェクトにキャンバスコンポーネントを付けたら軽くなるかもしれません。

**Comment by natsupy** [comment]
thank you for answer, i'm using these component in game object(A) using gradation
http://i.imgur.com/cNYHGn0.png
btw, if i'm using many child gameobject also using gradation in (A), maybe this make performance hight up ?

**Comment by eral** [comment]
It is more important not to call Gradation.ModifyMesh() than the number of gameobjects.
Gradation.ModifyMesh() is very heavy function, but it is not called by just scrolling.
Therefore scroll should be light.
[UnityUIExtention_Issues_1_1.gif (1.32MB)](https://gist.githubusercontent.com/eral/c6535f975aa199a0da56d501fe47ead0/raw/47e845a6d99d16aee947def0dd1468e60469165b/UnityUIExtention_Issues_1_1.gif)
I see your screen shot, Gradation.ModifyMesh() is called.
In other words, other components are calling Graphic.SetVerticesDirty().
If you remove the component calling Graphic.SetVerticesDirty(), I think that performance will be better.


Native language text(Japanese)
個数よりもGradation.ModifyMesh()を呼ばれない様にする方が重要です。
Gradation.ModifyMesh()は確かに重い関数なのですが、スクロールしただけでは呼び出されません。
故にスクロールは軽い筈なのです。
[UnityUIExtention_Issues_1_1.gif (1.32MB)](https://gist.githubusercontent.com/eral/c6535f975aa199a0da56d501fe47ead0/raw/47e845a6d99d16aee947def0dd1468e60469165b/UnityUIExtention_Issues_1_1.gif)
スクリーンショットを見る限りGradation.ModifyMesh()が呼ばれているので、他のコンポーネントがGraphic.SetVerticesDirty()を呼んでいるのでしょう。
Graphic.SetVerticesDirty()を呼んでいるコンポーネントを外せば軽くなると思います。

**Comment by natsupy** [comment]
thank you for your help, i'll try!
